---
s3:
  access_key_id: ((prod_s3_access_key_id))
  region_name: ((prod_s3_region_name))
  buckets:
    product: ((prod_pcf_product_bucket))
    config: ((prod_pcf_config_bucket))
  secret_access_key: ((prod_s3_secret_access_key))
  endpoint: ((prod_s3_endpoint))
pivnet_token: ((pivnet_token))
redis_version: ((redis_version))
opsman_target: ((prod_opsman_target))
opsman_user: ((prod_opsman_user))
opsman_password: ((prod_opsman_password))
opsman_skip_ssl_validation: true
opsman_decryption_passphrase: ((prod_opsman_passphrase))
redis-config:
  product-name: p-redis
  product-properties:
    .cf-redis-broker.redis_maxmemory:
      value: 512MB
    .cf-redis-broker.service_instance_limit:
      value: 5
    .dedicated-node.delete_dedicated_instances:
      value: true
    .properties.backups_selector:
      value: No Backups
    .properties.canary_org_space_selector:
      value: "No"
    .properties.large_plan_selector:
      value: Plan Inactive
    .properties.medium_plan_selector:
      value: Plan Inactive
    .properties.metrics_polling_interval:
      value: 30
    .properties.small_plan_selector:
      value: Plan Active
    .properties.syslog_selector:
      value: "No"
    .redis-on-demand-broker.maximum_parallel_upgrades:
      value: 1
    .redis-on-demand-broker.service_instance_limit:
      value: 20
    .redis-on-demand-broker.service_instance_sharing:
      value: false
    .redis-on-demand-broker.upgrade_canary_number:
      value: 1
  network-properties:
    network:
      name: Deployment
    other_availability_zones:
    - name: "null"
    service_network:
      name: Services
    singleton_availability_zone:
      name: "null"
  resource-config:
    cf-redis-broker:
      instances: automatic
      persistent_disk:
        size_mb: automatic
      instance_type:
        id: automatic
      internet_connected: false
    dedicated-node:
      instances: 0
      persistent_disk:
        size_mb: automatic
      instance_type:
        id: automatic
      internet_connected: false
    redis-on-demand-broker:
      instances: automatic
      instance_type:
        id: automatic
      internet_connected: false
  errand-config:
    broker-deregistrar:
      pre-delete-state: true
    broker-registrar:
      post-deploy-state: true
    cleanup-metadata-if-dedicated-disabled:
      post-deploy-state: true
    delete-all-service-instances-and-deregister-broker:
      pre-delete-state: true
    deprecate-dedicated-vm-plan:
      post-deploy-state: true
    on-demand-broker-smoke-tests:
      post-deploy-state: true
    register-broker:
      post-deploy-state: true
    smoke-tests:
      post-deploy-state: true
    upgrade-all-service-instances:
      post-deploy-state: true
