---
#┌───────────────────────────────────────────────────────────────────┐
#├ Globals                                                           │
#└───────────────────────────────────────────────────────────────────┘
s3:
  access_key_id: ((s3_access_key_id))
  region_name: ((s3_region_name))
  buckets:
    product: ((s3_product_bucket))
    config: ((s3_config_bucket))
  secret_access_key: ((s3_secret_access_key))
  endpoint: ((s3_endpoint))
opsman_image_wildcard: "OpsManager*.yml"
opsman_image_s3_versioned_regexp: "OpsManager2.3-(.*).146onAzure.yml"

#┌───────────────────────────────────────────────────────────────────┐
#├ Rendered into auth.yml                                            │
#└───────────────────────────────────────────────────────────────────┘
auth_config:
  username: ((opsman_user))
  password: ((opsman_password))
  decryption-passphrase: ((opsman_decryption_passphrase))

#┌───────────────────────────────────────────────────────────────────┐
#├ Rendered into env.yml                                             │
#└───────────────────────────────────────────────────────────────────┘
env_config:
  target: ((opsman_target))
  skip-ssl-validation: true
  username: ((opsman_user))
  password: ((opsman_password))
  connect-timeout: 1600
  request-timeout: 600

#┌───────────────────────────────────────────────────────────────────┐
#├ Rendered into opsman.yml                                          │
#└───────────────────────────────────────────────────────────────────┘
opsman_config:
  opsman-configuration:
    azure:
      subscription_id: ((iaas_configuration_subscription_id))
      resource_group: ((iaas_configuration_resource_group_name))
      tenant_id: ((iaas_configuration_tenant_id))
      client_id: ((iaas_configuration_client_id))
      client_secret: ((iaas_configuration_client_secret))
      location: "East US"
      public_ip: ((opsman_public_ip))
      private_ip: ((opsman_private_ip))
      container: opsmanager
      network_security_group: ((iaas_configuration_opsman_security_group))
      vpc_network: ((vpc_network))
      vpc_subnet: ((net_mgmt_subnet))
      storage_account: ((iaas_configuration_storage_account))
      storage_key: ((iaas_configuration_storage_key))
      ssh_public_key: ((iaas_configuration_ssh_public_key))
      vm_name: opsmanager
      boot_disk_size: 150

#┌───────────────────────────────────────────────────────────────────┐
#├ Rendered into director.yml                                        │
#└───────────────────────────────────────────────────────────────────┘
director_config:
  director-configuration:
    allow_legacy_agents: true
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    excluded_recursors: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {))
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: ntp.ubuntu.com
    post_deploy_enabled: false
    resurrector_enabled: true
    retry_bosh_deploys: true
  iaas-configuration:
    bosh_storage_account_name: ((iaas_configuration_storage_account))
    client_id: ((iaas_configuration_client_id))
    client_secret: ((iaas_configuration_client_secret))
    default_security_group: ((iaas_configuration_default_security_group))
    deployments_storage_account_name: ((iaas_configuration_deployments_storage_account_name))
    environment: ((iaas_configuration_environment))
    resource_group_name: ((iaas_configuration_resource_group_name))
    ssh_public_key: ((iaas_configuration_ssh_public_key))
    ssh_private_key: ((iaas_configuration_ssh_private_key))
    cloud_storage_type: managed_disks
    storage_account_type: Standard_LRS
    subscription_id: ((iaas_configuration_subscription_id))
    tenant_id: ((iaas_configuration_tenant_id))
  network-assignment:
    network:
      name: Management
    other_availability_zones:
    - name: "null"
    singleton_availability_zone:
      name: "null"
  networks-configuration:
    icmp_checks_enabled: false
    networks:
    - name: Management
      subnets:
      - iaas_identifier: ((net_mgmt_iaas_id))
        cidr: 10.0.8.0/20
        dns: 168.63.129.16
        gateway: 10.0.8.1
        reserved_ip_ranges: 10.0.8.1-10.0.8.11
        availability_zone_names:
        - "null"
    - name: Deployment
      subnets:
      - iaas_identifier: ((net_dep_iaas_id))
        cidr: 10.0.0.0/22
        dns: 168.63.129.16
        gateway: 10.0.0.1
        reserved_ip_ranges: 10.0.0.1-10.0.0.9
        availability_zone_names:
        - "null"
    - name: Services
      subnets:
      - iaas_identifier: ((net_svcs_iaas_id))
        cidr: 10.0.4.0/22
        dns: 168.63.129.16
        gateway: 10.0.4.1
        reserved_ip_ranges: 10.0.4.1-10.0.4.9
        availability_zone_names:
        - "null"
  resource-configuration:
    compilation:
      instances: automatic
      instance_type:
        id: automatic
      internet_connected: false
    director:
      instances: automatic
      persistent_disk:
        size_mb: "102400"
      instance_type:
        id: automatic
      internet_connected: false
  security-configuration:
    generate_vm_passwords: true
  syslog-configuration:
    enabled: false
  vmextensions-configuration: []
