---
#┌───────────────────────────────────────────────────────────────────┐
#├ Globals                                                           │
#└───────────────────────────────────────────────────────────────────┘
s3:
  access_key_id: ((s3_access_key_id))
  region_name: ((s3_region_name))
  buckets:
    product: ((product_bucket))
    config: ((config_bucket))
  secret_access_key: ((s3_secret_access_key))
  endpoint: ((s3_endpoint))
opsman_image_s3_versioned_regexp: "OpsManager2.3-(.*).146onAzure.yml"

#┌───────────────────────────────────────────────────────────────────┐
#├ Rendered into auth.yml                                            │
#└───────────────────────────────────────────────────────────────────┘
auth_config:
  username: ((opsman_username))
  password: ((opsman_password))
  decryption-passphrase: ((opsman_decryption_passphrase))

#┌───────────────────────────────────────────────────────────────────┐
#├ Rendered into env.yml                                             │
#└───────────────────────────────────────────────────────────────────┘
env_config:
  target: ((opsman_target))
  skip-ssl-validation: true
  username: ((opsman_username))
  password: ((opsman_password))
  connect-timeout: 1600
  request-timeout: 600

#┌───────────────────────────────────────────────────────────────────┐
#├ Rendered into opsman.yml                                          │
#└───────────────────────────────────────────────────────────────────┘
opsman_config:
  opsman-configuration:
    azure:
      subscription_id: ((opsman_subscription_id))
      resource_group: ((opsman_resource_group_name))
      tenant_id: ((opsman_tenant_id))
      client_id: ((opsman_client_id))
      client_secret: ((opsman_client_secret))
      location: "Central US"
      public_ip: ((opsman_public_ip))
      private_ip: ((opsman_private_ip))
      container: ((opsman_storage_container))
      network_security_group: ((opsman_security_group))
      vpc_network: ((opsman_network))
      vpc_subnet: ((opsman_subnet))
      storage_account: ((opsman_storage_account))
      storage_key: ((opsman_storage_key))
      ssh_public_key: ((opsman_ssh_public_key))
      vm_name: opsmanager
      boot_disk_size: 150

#┌───────────────────────────────────────────────────────────────────┐
#├ Rendered into director.yml                                        │
#└───────────────────────────────────────────────────────────────────┘
director_config:
  director-configuration:
    allow_legacy_agents: true
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    excluded_recursors: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: ntp.ubuntu.com
    post_deploy_enabled: false
    resurrector_enabled: true
    retry_bosh_deploys: true
  iaas-configuration:
    bosh_storage_account_name: ((director_storage_account))
    client_id: ((director_client_id))
    client_secret: ((director_client_secret))
    default_security_group: ((director_default_security_group))
    deployments_storage_account_name: ((director_deployments_storage_account))
    environment: ((director_environment))
    resource_group_name: ((director_resource_group_name))
    ssh_public_key: ((director_ssh_public_key))
    ssh_private_key: ((director_ssh_private_key))
    cloud_storage_type: managed_disks
    storage_account_type: Standard_LRS
    subscription_id: ((director_subscription_id))
    tenant_id: ((director_tenant_id))
  network-assignment:
    network:
      name: Management
    other_availability_zones:
    - name: "null"
    singleton_availability_zone:
      name: "null"
  networks-configuration:
    icmp_checks_enabled: false
    networks:
    - name: Management
      subnets:
      - iaas_identifier: ((net_mgmt_iaas_id))
        cidr: 10.1.8.0/26
        dns: 168.63.129.16
        gateway: 10.1.8.1
        reserved_ip_ranges: 10.1.8.1-10.1.8.9
        availability_zone_names:
        - "null"
    - name: Deployment
      subnets:
      - iaas_identifier: ((net_dep_iaas_id))
        cidr: 10.1.0.0/22
        dns: 168.63.129.16
        gateway: 10.1.0.1
        reserved_ip_ranges: 10.1.0.1-10.1.0.9
        availability_zone_names:
        - "null"
    - name: Services
      subnets:
      - iaas_identifier: ((net_svcs_iaas_id))
        cidr: 10.1.4.0/22
        dns: 168.63.129.16
        gateway: 10.1.4.1
        reserved_ip_ranges: 10.1.4.1-10.1.4.9
        availability_zone_names:
        - "null"
  resource-configuration:
    compilation:
      instances: automatic
      instance_type:
        id: automatic
      internet_connected: false
    director:
      instances: automatic
      persistent_disk:
        size_mb: "102400"
      instance_type:
        id: automatic
      internet_connected: false
  security-configuration:
    generate_vm_passwords: true
  syslog-configuration:
    enabled: false
  vmextensions-configuration: []
