resources:
- name: pcf-automation-tasks
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    bucket: ((s3.buckets.product))
    region_name: ((s3.region_name))
    endpoint: ((s3.endpoint))
    secret_access_key: ((s3.secret_access_key))
    regexp: .*tasks-(.*).zip

- name: pcf-automation-image
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    bucket: ((s3.buckets.product))
    region_name: ((s3.region_name))
    endpoint: ((s3.endpoint))
    secret_access_key: ((s3.secret_access_key))
    regexp: platform-automation-image-(.*).tgz

- name: product
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    bucket: ((s3.buckets.product))
    region_name: ((s3.region_name))
    endpoint: ((s3.endpoint))
    secret_access_key: ((s3.secret_access_key))
    regexp: ((product_regexp))

- name: pipeline-utilities
  type: git
  source:
    uri: https://github.com/pivotalservices/pipeline-utilities.git

jobs:
- name: download-from-pivnet-and-upload-to-om
  plan:
  - get: pipeline-utilities
  - task: create-env-file
    file: pipeline-utilities/tasks/create-env-file.yml
    params:
      OPSMAN_TARGET: ((opsman_target))
      OPSMAN_SKIP_SSL_VALIDATION: ((opsman_skip_ssl_validation))
      OPSMAN_USERNAME: ((opsman_user))
      OPSMAN_PASSWORD: ((opsman_password))
      OPSMAN_DECRYPTION_PASSPHRASE: ((opsman_decryption_passphrase))
      OPSMAN_CONNECT_TIMEOUT: 1600
  - task: download-product-from-pivnet
    params:
      PIVNET_TOKEN: ((pivnet_token))
      PRODUCT_NAME: ((product_slug_name))
      PRODUCT_VERSION: ((product_version))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pmatuska/pivnet-cli
          tag: v2
      inputs:
        - name: env
      run:
        path: bash
        args:
        - "-c"
        - |
          pivnet login --api-token=${PIVNET_TOKEN}
          if [ `pivnet release-dependencies -p ${PRODUCT_NAME} -r ${PRODUCT_VERSION}| grep -c Xenial` -gt 0 ]
          then
            STEMCELL_TYPE=stemcells-ubuntu-xenial
          else
            STEMCELL_TYPE=stemcells
          fi
          STEMCELL_VER=`pivnet release-dependencies -p ${PRODUCT_NAME} -r ${PRODUCT_VERSION}| grep -i Stemcells| awk -F"|" '{ print $3 }'| sort -rn| head -1| sed -e 's/\ //g'`
          STEMCELL_EXISTS=`om --env env/env.yml curl --path /api/v0/stemcell_assignments | jq '.. | .version? // empty'| grep -c ${STEMCELL_VER}`
          if [ ${STEMCELL_EXISTS} -lt 1 ]
          then
            pivnet download-product-files -p ${STEMCELL_TYPE} -r ${STEMCELL_VER} -g "*azure*" --accept-eula
            om --env env/env.yml upload-stemcell -s *.tgz
          else
            echo "Stemcell is already uploaded in OM."
          fi

- name: upload-and-stage-((config.product-name))
  serial: true
  plan:
  - get: pipeline-utilities
  - task: create-env-file
    file: pipeline-utilities/tasks/create-env-file.yml
    params:
      OPSMAN_TARGET: ((opsman_target))
      OPSMAN_SKIP_SSL_VALIDATION: ((opsman_skip_ssl_validation))
      OPSMAN_USERNAME: ((opsman_user))
      OPSMAN_PASSWORD: ((opsman_password))
      OPSMAN_DECRYPTION_PASSPHRASE: ((opsman_decryption_passphrase))
      OPSMAN_CONNECT_TIMEOUT: 1600
      OPSMAN_REQUEST_TIMEOUT: 1800
  - aggregate:
    - get: pcf-automation-image
      params:
        unpack: true
    - get: pcf-automation-tasks
      params:
        unpack: true
    - get: product
  - task: upload-and-stage-product
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/upload-and-stage-product.yml
    input_mapping:
      product: product
    params:
      ENV_FILE: env.yml

- name: configure-((config.product-name))
  serial: true
  plan:
  - aggregate:
    - get: pipeline-utilities
    - get: pcf-automation-image
      params:
        unpack: true
    - get: pcf-automation-tasks
      params:
        unpack: true
      passed:
      - upload-and-stage-((config.product-name))
      trigger: true
  - task: create-env-file
    file: pipeline-utilities/tasks/create-env-file.yml
    params:
      OPSMAN_TARGET: ((opsman_target))
      OPSMAN_SKIP_SSL_VALIDATION: ((opsman_skip_ssl_validation))
      OPSMAN_USERNAME: ((opsman_user))
      OPSMAN_PASSWORD: ((opsman_password))
      OPSMAN_DECRYPTION_PASSPHRASE: ((opsman_decryption_passphrase))
      OPSMAN_CONNECT_TIMEOUT: 1600
      OPSMAN_REQUEST_TIMEOUT: 600
  - task: generate-((config.product-name))-config
    params:
      CONFIG: ((config))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pivotalservices/bosh2-docker
      outputs:
        - name: config
      run:
        path: bash
        args:
        - "-c"
        - |
          bosh int <(awk -v ORS='\\n' '1' <(echo "${CONFIG}" | tr -d '\r')) > config/((config.product-name))-config.yml
  - task: configure-((config.product-name))
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/configure-product.yml
    params:
      CONFIG_FILE: ((config.product-name))-config.yml
      ENV_FILE: env.yml

- name: apply-product-changes
  serial: true
  plan:
  - aggregate:
    - get: pcf-automation-image
      params:
        unpack: true
    - get: pcf-automation-tasks
      params:
        unpack: true
      passed:
      - configure-((config.product-name))
      trigger: true
    - get: pipeline-utilities
  - task: create-env-file
    file: pipeline-utilities/tasks/create-env-file.yml
    params:
      OPSMAN_TARGET: ((opsman_target))
      OPSMAN_SKIP_SSL_VALIDATION: ((opsman_skip_ssl_validation))
      OPSMAN_USERNAME: ((opsman_user))
      OPSMAN_PASSWORD: ((opsman_password))
      OPSMAN_DECRYPTION_PASSPHRASE: ((opsman_decryption_passphrase))
      OPSMAN_CONNECT_TIMEOUT: 1600
  - task: apply-((config.product-name))-changes
    image: pcf-automation-image
    config:
      platform: linux
      inputs:
        - name: env
      run:
        path: bash
        args:
          - "-c"
          - |
            om --env=env/env.yml apply-changes --product-name=((config.product-name))

- name: staged-((config.product-name))-config
  plan:
  - aggregate:
    - get: pcf-automation-image
      params:
        unpack: true
    - get: pcf-automation-tasks
      params:
        unpack: true
    - get: pipeline-utilities
  - task: create-env-file
    file: pipeline-utilities/tasks/create-env-file.yml
    params:
      OPSMAN_TARGET: ((opsman_target))
      OPSMAN_SKIP_SSL_VALIDATION: ((opsman_skip_ssl_validation))
      OPSMAN_USERNAME: ((opsman_user))
      OPSMAN_PASSWORD: ((opsman_password))
      OPSMAN_DECRYPTION_PASSPHRASE: ((opsman_decryption_passphrase))
      OPSMAN_CONNECT_TIMEOUT: 1600
  - task: staged-config
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/staged-config.yml
    params:
      PRODUCT_NAME: ((config.product-name))
      ENV_FILE: env.yml
