---
s3:
  access_key_id: ((prod_s3_access_key_id))
  region_name: ((prod_s3_region_name))
  buckets:
    product: ((prod_pcf_product_bucket))
    config: ((prod_pcf_config_bucket))
  secret_access_key: ((prod_s3_secret_access_key))
  endpoint: ((prod_s3_endpoint))
pivnet_token: ((pivnet_token))
rabbitmq_version: ((rabbitmq_version))
opsman_target: ((prod_opsman_target))
opsman_user: ((prod_opsman_user))
opsman_password: ((prod_opsman_password))
opsman_skip_ssl_validation: true
opsman_decryption_passphrase: ((prod_opsman_passphrase))
spring-cloud-services-config:
  product-name: p-spring-cloud-services
  product-properties:
    .deploy-service-broker.broker_max_instances:
      value: 100
    .deploy-service-broker.disable_cert_check:
      value: false
    .deploy-service-broker.message_bus_service:
      value: p.rabbitmq
    .deploy-service-broker.message_bus_service_plan:
      value: single-node-3.7
    .deploy-service-broker.persistence_store_service:
      value: p.mysql
    .deploy-service-broker.persistence_store_service_plan:
      value: db-small
    .deploy-service-broker.secure_credentials:
      value: false
    .register-service-broker.enable_global_access:
      value: true
  network-properties:
    network:
      name: Services
    other_availability_zones:
    - name: "null"
    singleton_availability_zone:
      name: "null"
  resource-config:
    deploy-service-broker:
      instances: automatic
      instance_type:
        id: automatic
      internet_connected: false
    destroy-service-broker:
      instances: automatic
      instance_type:
        id: automatic
      internet_connected: false
    register-service-broker:
      instances: automatic
      instance_type:
        id: automatic
      internet_connected: false
    run-smoke-tests:
      instances: automatic
      instance_type:
        id: automatic
      internet_connected: false
  errand-config:
    deploy-service-broker:
      post-deploy-state: true
    destroy-service-broker:
      pre-delete-state: true
    register-service-broker:
      post-deploy-state: true
    run-smoke-tests:
      post-deploy-state: true
