---
s3:
  access_key_id: ((prod_s3_access_key_id))
  region_name: ((prod_s3_region_name))
  buckets:
    product: ((prod_pcf_product_bucket))
    config: ((prod_pcf_config_bucket))
  secret_access_key: ((prod_s3_secret_access_key))
  endpoint: ((prod_s3_endpoint))
pivnet_token: ((pivnet_token))
rabbitmq_version: ((rabbitmq_version))
opsman_target: ((prod_opsman_target))
opsman_user: ((prod_opsman_user))
opsman_password: ((prod_opsman_password))
opsman_skip_ssl_validation: true
opsman_decryption_passphrase: ((prod_opsman_passphrase))
rabbitmq-config:
  product-name: p-rabbitmq
  product-properties:
    .on-demand-broker.global_service_instance_quota:
      value: 20
    .properties.enable_tls_selector:
      value: disabled
    .properties.global_settings_secure_bindings:
      value: "No"
    .properties.global_settings_shareable_instances:
      value: "No"
    .properties.metrics_polling_interval:
      value: 30
    .properties.multitenant_support:
      value: disabled
    .properties.on_demand_broker_plan_1_cf_service_access:
      value: disable
    .properties.on_demand_broker_plan_1_description:
      value: This plan provides a single dedicated RabbitMQ 3.7 node
    .properties.on_demand_broker_plan_1_disk_limit_acknowledgement:
      value:
      - acknowledge
    .properties.on_demand_broker_plan_1_features:
      value: RabbitMQ 3.7
    .properties.on_demand_broker_plan_1_instance_quota:
      value: 10
    .properties.on_demand_broker_plan_1_name:
      value: single-node-3.7
    .properties.on_demand_broker_plan_1_rabbitmq_az_placement:
      value:
      - "null"
    .properties.on_demand_broker_plan_1_rabbitmq_cluster_partition_handling_strategy:
      value: pause_minority
    .properties.on_demand_broker_plan_1_rabbitmq_number_of_nodes:
      value: 1
    .properties.on_demand_broker_plan_2_selector:
      value: disabled
    .properties.on_demand_broker_plan_3_selector:
      value: disabled
    .properties.on_demand_broker_plan_4_selector:
      value: disabled
    .properties.on_demand_broker_plan_5_selector:
      value: disabled
    .properties.syslog_selector:
      value: disabled
  network-properties:
    network:
      name: Deployment
    other_availability_zones:
    - name: "null"
    service_network:
      name: Services
    singleton_availability_zone:
      name: "null"
  resource-config:
    on-demand-broker:
      instances: automatic
      persistent_disk:
        size_mb: automatic
      instance_type:
        id: automatic
      internet_connected: false
    rabbitmq-broker:
      instances: 0
      instance_type:
        id: automatic
      internet_connected: false
    rabbitmq-haproxy:
      instances: 0
      instance_type:
        id: automatic
      internet_connected: false
    rabbitmq-server:
      instances: 0
      persistent_disk:
        size_mb: automatic
      instance_type:
        id: automatic
      internet_connected: false
  errand-config:
    broker-deregistrar:
      pre-delete-state: true
    broker-registrar:
      post-deploy-state: true
    delete-all-service-instances:
      pre-delete-state: true
    deregister-broker:
      pre-delete-state: true
    on-demand-broker-smoke-tests:
      post-deploy-state: true
    register-broker:
      post-deploy-state: true
    smoke-tests:
      post-deploy-state: true
    upgrade-all-service-instances:
      post-deploy-state: true
